### PR TITLE
ci: use yarn cache

### PR DESCRIPTION
**Pull request by DanielRuf**
This uses the yarn cache for builds to speed them up.

### CODE REVIEW

**Comment by RIP21** [comment]
Is already in the codebase. Thanks.

**Comment by DanielRuf** [comment]
Because you added it 5 hours ago ;-) You could have also used my code =)

**Comment by RIP21** [comment]
Yes, but I added these changes, and than started to clean up PRs :/ Sorry, also it was complaining that it's not possible to merge and even if I would like, it would take me lots of time to wait for your merge from upstream, which is looong story.
Anyway, thanks for input.

**Comment by DanielRuf** [comment]
> it's not possible to merge

I guess this is because there are changes on master and this branch had to be rebased on master.

No problem, thanks for maintaining and cleaning up =)

**Comment by RIP21** [comment]
@DanuelRuf BTW. Please, review PR with name. v2. What do you think?

**Pull request closed without merging**
